volumes:
  {{ cookiecutter.project_slug }}_local_postgres_data: {}
  {{ cookiecutter.project_slug }}_local_postgres_data_backups: {}
  {% if cookiecutter.use_celery == 'y' %}{{ cookiecutter.project_slug }}_local_redis_data: {}{% endif %}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    container_name: {{ cookiecutter.project_slug }}_local_django
    depends_on:
      - postgres
      {%- if cookiecutter.use_celery == 'y' %}
      - redis
      {%- endif %}
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    container_name: {{ cookiecutter.project_slug }}_local_postgres
    volumes:
      - {{ cookiecutter.project_slug }}_local_postgres_data:/var/lib/postgresql/data
      - {{ cookiecutter.project_slug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  {%- if cookiecutter.use_mailpit == 'y' %}

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: {{ cookiecutter.project_slug }}_local_mailpit
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if cookiecutter.use_celery == 'y' %}

  redis:
    image: docker.io/redis:7.2
    container_name: {{ cookiecutter.project_slug }}_local_redis
    volumes:
      - {{ cookiecutter.project_slug }}_local_redis_data:/data

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celeryworker
    container_name: {{ cookiecutter.project_slug }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celerybeat
    container_name: {{ cookiecutter.project_slug }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_flower
    container_name: {{ cookiecutter.project_slug }}_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  {%- endif %}
  {%- if cookiecutter.monitoring == 'Prometheus' or cookiecutter.monitoring == 'Grafana' %}

  prometheus:
    build:
      context: .
      dockerfile: ./compose/local/prometheus/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_prometheus
    container_name: {{ cookiecutter.project_slug }}_local_prometheus
    ports:
      - '9090:9090'
    depends_on:
      - django
    volumes:
      - ./compose/local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./compose/local/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro

  {%- endif %}
  {%- if cookiecutter.monitoring == 'Grafana' %}

  grafana:
    build:
      context: .
      dockerfile: ./compose/local/grafana/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_grafana
    container_name: {{ cookiecutter.project_slug }}_local_grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./compose/local/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin

  {%- endif %}
