global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "{{ cookiecutter.project_name }}-monitor"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "/etc/prometheus/alert-rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django-app"
    static_configs:
      - targets: ["django:8000"]
    metrics_path: "/metrics/"
    scrape_interval: 10s
    scrape_timeout: 5s
